### PR TITLE
Update LBT14 to use correct denom

### PR DESCRIPTION
**Pull request by edelarua**
Downstream changes resulting from https://github.com/insightsengineering/tern/pull/1326. No other templates are affected.

### CODE REVIEW

**Comment by edelarua** [comment]
@shajoezhu is tlg-catalog set up to use staged dependencies in the development profile? If not, this one may have to wait until the tern PR is merged to pass checks

**Comment by shajoezhu** [comment]
> @shajoezhu is tlg-catalog set up to use staged dependencies in the development profile? If not, this one may have to wait until the tern PR is merged to pass checks

it should

https://github.com/insightsengineering/tlg-catalog/blob/main/package/staged_dependencies.yaml

not sure why it is not picking up changes in tern? hi @cicdguy please could you take a look?

**Comment by shajoezhu** [comment]
hi @cicdguy , i think this is not working, I made a manual vbump on https://github.com/insightsengineering/tern/pull/1326/files, v0.9.6.9007. it seems in the PR currently, it is fetching from main. So the staged.dependencies, has not worked.

**Comment by pawelru** [comment]
You are right - staged.dependencies is skipped and all the dependencies are installed from r-universe:
image

This is why:
https://github.com/insightsengineering/tlg-catalog/blob/b64b542551969bafd358162aed2247a06a3e2fc8/.github/workflows/check.yml#L43
https://github.com/insightsengineering/r.pkg.template/blob/da0ba8e247827b92b59edd8c064388eb55948b88/.github/workflows/build-check-install.yaml#L378-L380

The rationale is to enable WebR. WebR checks how the packages are installed and request wasm binaries accordingly. When installed from sources (e.g. via staged.deps) there were some errors - not sure if it's still the case.

Is this a blocker for you? As we are right before changing this into pak-based installation - I don't think it would be wise for us to enable staged deps right now. Can you do test after merge to tern devel?

**Comment by shajoezhu** [comment]
> You are right - staged.dependencies is skipped and all the dependencies are installed from r-universe: image
> 
> This is why:
> 
> https://github.com/insightsengineering/tlg-catalog/blob/b64b542551969bafd358162aed2247a06a3e2fc8/.github/workflows/check.yml#L43
> 
> 
> https://github.com/insightsengineering/r.pkg.template/blob/da0ba8e247827b92b59edd8c064388eb55948b88/.github/workflows/build-check-install.yaml#L378-L380
> The rationale is to enable WebR. WebR checks how the packages are installed and request wasm binaries accordingly. When installed from sources (e.g. via staged.deps) there were some errors - not sure if it's still the case.
> 
> Is this a blocker for you? As we are right before changing this into pak-based installation - I don't think it would be wise for us to enable staged deps right now. Can you do test after merge to tern devel?

Thanks @pawelru for the explanation, it is not a blocker for us, as we are checked via scda.test, and we can merge tern, scda.test, then update tlg-c code after. Just need to redefine the workflow, and perhaps good idea to record these somewhere. I support the change, just want to better prepare for this change, and make sure it is a smooth transtion, rather than a hardlanding, and breaking changes everywhere. 

If we were going to use pak for updating rtables/tern/formatters/rlistings, how should we make change during the process in tlg-c

**Comment by pawelru** [comment]
> If we were going to use pak for updating rtables/tern/formatters/rlistings, how should we make change during the process in tlg-c

The good thing about that is that these are independent so that changes elsewhere (rtables/tern/...) are independent to what's here. You don't have to coordinate it across repos. 
TLG-C is one of the few repos in which we are using WebR and that actually might create some issues. I can definitely help on this.

**Comment by shajoezhu** [comment]
thanks a lot Pawel!

**Comment by edelarua** [comment]
@shajoezhu this is now passing!

**Review by shajoezhu — APPROVED** [review]
lgtm! Thanks a lot @edelarua

**Pull request merged**
