### PR TITLE
close #272

### LINKED ISSUE #272: fix R CMD CHECK notes
* checking for hidden files and directories ... NOTE
Found the following hidden files and directories:
  tests/testthat/_book/assets/www/.gitkeep
  tests/testthat/_book/assets/www/lock/.gitkeep
  tests/testthat/_data/.rbuildkeep
These were most likely included in error. See section ‘Package
structure’ in the ‘Writing R Extensions’ manual.
* checking for portable file names ... NOTE
Found the following non-portable file paths:
  tlg.catalog.pkg/tests/testthat/_book/_extensions/coatless/webr/qwebr-document-engine-initialization.js
  tlg.catalog.pkg/tests/testthat/_book/_extensions/quarto-ext/fontawesome/assets/css/latex-fontsize.css
  tlg.catalog.pkg/tests/testthat/_book/_extensions/quarto-ext/fontawesome/assets/webfonts/fa-brands-400.ttf
  tlg.catalog.pkg/tests/testthat/_book/_extensions/quarto-ext/fontawesome/assets/webfonts/fa-brands-400.woff2
  tlg.catalog.pkg/tests/testthat/_book/_extensions/quarto-ext/fontawesome/assets/webfonts/fa-regular-400.ttf
  tlg.catalog.pkg/tests/testthat/_book/_extensions/quarto-ext/fontawesome/assets/webfonts/fa-regular-400.woff2
  tlg.catalog.pkg/tests/testthat/_book/_extensions/quarto-ext/fontawesome/assets/webfonts/fa-solid-900.ttf
  tlg.catalog.pkg/tests/testthat/_book/_extensions/quarto-ext/fontawesome/assets/webfonts/fa-solid-900.woff2
  tlg.catalog.pkg/tests/testthat/_book/_extensions/quarto-ext/fontawesome/assets/webfonts/fa-v4compatibility.ttf
  tlg.catalog.pkg/tests/testthat/_book/_extensions/quarto-ext/fontawesome/assets/webfonts/fa-v4compatibility.woff2
  tlg.catalog.pkg/tests/testthat/_book/_extensions/quarto-ext/fontawesome/assets/webfonts/FontAwesome6Brands-Regular-400.ttf
  tlg.catalog.pkg/tests/testthat/_book/_extensions/quarto-ext/fontawesome/assets/webfonts/FontAwesome6Brands-Regular-400.woff2
  tlg.catalog.pkg/tests/testthat/_book/_extensions/quarto-ext/fontawesome/assets/webfonts/FontAwesome6Free-Regular-400.ttf
  tlg.catalog.pkg/tests/testthat/_book/_extensions/quarto-ext/fontawesome/assets/webfonts/FontAwesome6Free-Regular-400.woff2
  tlg.catalog.pkg/tests/testthat/_book/_extensions/quarto-ext/fontawesome/assets/webfonts/FontAwesome6Free-Solid-900.ttf
  tlg.catalog.pkg/tests/testthat/_book/_extensions/quarto-ext/fontawesome/assets/webfonts/FontAwesome6Free-Solid-900.woff2
  tlg.catalog.pkg/tests/testthat/_book/_extensions/quarto-ext/shinylive/resources/css/shinylive-quarto.css

### PR DESCRIPTION
**Pull request by shajoezhu**

### CODE REVIEW

**Comment by pawelru** [comment]
There are still notes reported in CI:

```
* checking for portable file names ... NOTE
Found the following non-portable file paths:
  tlg.catalog.pkg/tests/testthat/_book/_extensions/quarto-ext/fontawesome/assets/css/latex-fontsize.css
  tlg.catalog.pkg/tests/testthat/_book/_extensions/quarto-ext/shinylive/resources/css/shinylive-quarto.css

Tarballs are only required to store paths of up to 100 bytes and cannot
store those of more than 256 bytes, with restrictions including to 100
bytes for the final component.
See section ‘Package structure’ in the ‘Writing R Extensions’ manual.
```

**Review by pawelru — CHANGES_REQUESTED** [review]
still not there yet - see my previous comment

**Comment by m7pr** [comment]
Warning is weird as the folder is empty https://github.com/insightsengineering/tlg-catalog/blob/main/package/tests/testthat/_book

**Comment by pawelru** [comment]
> Warning is weird as the folder is empty https://github.com/insightsengineering/tlg-catalog/blob/main/package/tests/testthat/_book

No it's not. This is how GitHub present symlinks

**Comment by pawelru** [comment]
Went with an alternative https://github.com/insightsengineering/tlg-catalog/pull/274

**Pull request closed without merging**
