### PR TITLE
Revert RATET01 updates (temporarily)

### LINKED ISSUE #196: temporary removal for rate01 (due to change after tern 0.9.3), reinstate after tmc cran release

### PR DESCRIPTION
**Pull request by edelarua**
Closes #196

### CODE REVIEW

**Comment by edelarua** [comment]
@shajoezhu is it possible to bypass this error? https://github.com/insightsengineering/tlg-catalog/actions/runs/7645226321/job/20831300259?pr=197#step:40:69

**Comment by shajoezhu** [comment]
hi @cicdguy and @walkowif , I was wondering if you could give us some pointers here please. Thanks so much!

**Comment by shajoezhu** [comment]
after discussion, we decided to have tmc's tern version to be >= 0.9.3, and hope this will work. @walkowif @cicdguy fyi, I will deal with CRAN's backwards failure check next time when I submitting tern, and inform that there will be a tmc rerelease to accommodate with the next tern release.

**Review by shajoezhu — APPROVED** [review]
lgtm! Thanks @edelarua

**Pull request merged**
