### PR TITLE
Move kmg01 from 'Graph - Other' to 'Graph - Eficacy'

### PR DESCRIPTION
**Pull request by martincadek**
This PR should resolve [issue 195](https://github.com/insightsengineering/tlg-catalog/issues/195). 

I refreshed the `tlg-index.qmd` using the R script.

No other changes were made, assuming the rendering is done automatically from this point.

It's my first contribution, apologies in case there are any issues, happy to get any feedback.

### CODE REVIEW

**Review by edelarua — APPROVED** [review]
Lgtm! Thanks @martincadek 

I regenerated the index again just to keep it consistent. I think you must have a difference in your setup causing file names to alphabetize a bit differently, but it's not really an issue. Otherwise all good!

**Comment by edelarua** [comment]
Also - for future reference, when you make a PR also make sure you add it to the "NESTDevs" project board and then select the current sprint for better visibility :)

**Comment by shajoezhu** [comment]
hi @martincadek , the cicd is failing due to https://github.com/insightsengineering/tlg-catalog/actions/runs/8117167445/job/22190700077?pr=229#step:5:67

the error says " A branch or tag with the name '195_move_KMG01' could not be found"

can you please close this PR, and raise it again from this repo, instead of your fork please. thank you！

**Comment by edelarua** [comment]
> @edelarua Thanks for the helpful pointers, can I just clarify the last point? Did you mean that instead of a fork I should start off from insightsengineering? Is it fine if I set the format `issue#_description@main` manually? I think I can't automate that from Ocean.

Yes - instead of a fork it should be raised directly from the `tlg-catalog` repo. Its fine to name the branch manually. Joe should be able to help you get access if you don't already have it!

**Comment by martincadek** [comment]
> Lgtm! Thanks @martincadek
> 
> I regenerated the index again just to keep it consistent. I think you must have a difference in your setup causing file names to alphabetize a bit differently, but it's not really an issue. Otherwise all good!

@edelarua Do you please have any hints as to what might be the difference? I see that it alphabetises names with _suffix incorrectly? E.g.: LBL01_RLS will go first.

**Comment by edelarua** [comment]
> @edelarua Do you please have any hints as to what might be the difference? I see that it alphabetises names with _suffix incorrectly? E.g.: LBL01_RLS will go first.

I'm not sure why but I've seen other people having the same issue before so it's not just your computer.

**Pull request closed without merging**
