### PR TITLE
Update `RATET01` snapshot

### LINKED ISSUE #262: Fix `RATET01` snapshot
Integration tests are currently failing due to the `RATET01` snapshot which now has additional indentation.

### PR DESCRIPTION
**Pull request by edelarua**
Closes #262

### CODE REVIEW

**Review by shajoezhu — APPROVED** [review]
lgtm! Thanks @edelarua

**Comment by edelarua** [comment]
Hi @shajoezhu,

The integration tests for tlg-catalog test the stable version of the package but using the latest versions of the package dependencies so are not in sync with the stable version tested on GitHub via R CMD Check. Because of this, the current version of tlg-catalog is passing the checks on GitHub but not the integration tests, and if this PR is merged in integration tests will pass but the GitHub checks will fail.

Is it possible to change the integration tests to match the GH checks so that both can pass? If not, we should probably leave the integration tests failing until the next release of rtables so the catalog does not break.

**Comment by shajoezhu** [comment]
Hi @edelarua 
I think we should follow the order that package test pass first, before considering integration test. so I am inclined to hold this one off a bit longer. what do you think? FYI @pawelru

**Comment by pawelru** [comment]
> The integration tests for tlg-catalog test the stable version of the package but using the latest versions of the package dependencies

This feels to me like an error in the test setup. Let's feedback this to IDR team and see what can be done.

**Comment by edelarua** [comment]
The mismatch has been fixed by changing integration tests to use the devel version, so tests should be passing now.

**Pull request merged**
