### PR TITLE
add a negative binomial example to ratet01

### LINKED ISSUE #21: Add Negative Binomial example to the `RATET01` template
Depends on https://github.com/insightsengineering/tern/issues/857

To do:
- [x] Add a new "customized table 2" tab in [main/book/tables/efficacy/ratet01.qmd](https://github.com/insightsengineering/tlg-catalog/blob/main/book/tables/efficacy/ratet01.qmd?rgh-link-date=2024-01-09T08%3A41%3A18Z) and add a negative binomial example there

### PR DESCRIPTION
**Pull request by duanx9**
Close #21 per title description

### CODE REVIEW

**Comment by shajoezhu** [comment]
This looks very nice! All functions work very well together. 

image

Hi @danielinteractive , I was wondering what you think, if this is ok? It seems nice to have two method results together. Or should we follow the original request, and create a separate new tab instead? I was having trouble finding the original design of the template rate01, not available in gdsr?

**Comment by danielinteractive** [comment]
Thanks @duanx9 and @shajoezhu for the nice work!
I think it is fine to be able to have them together. That means, we could still just select one of the methods and display one single method's result in the table, right? Then it is fine.
I am not sure if there was any existing GDSR template. All this count stuff is pretty rare.

**Comment by shajoezhu** [comment]
> I think it is fine to be able to have them together. That means, we could still just select one of the methods and display one single method's result in the table, right? Then it is fine.
Yes, that is correct. It's just a new section appended. 

Thanks @danielinteractive , I will approve this PR now then :)

**Review by shajoezhu — APPROVED** [review]
lgtm! Many thanks! @duanx9

**Pull request merged**
