### PR TITLE
Add ADAL01

### LINKED ISSUE #37: Add ADAL01
Template design was completed on GitLab but never added to TLG-C.

### PR DESCRIPTION
**Pull request by edelarua**
[Design](https://code.roche.com/nest/docs/tlg-catalog/devel/-/issues/117) completed by Valentin in 2022 but never added to TLG-C.

Closes #37

### CODE REVIEW

**Comment by shajoezhu** [comment]
Thanks @edelarua , I think we need to hold this off until adab is refactored. @qiliu1013 , what do you think?

**Comment by shajoezhu** [comment]
hi @qiliu1013 , can you take a look at this template please? Thanks!

**Review by Melkiades — COMMENTED** [review]
I think this is good to go if we have this design already done @shajoezhu @edelarua

**Comment by shajoezhu** [comment]
hi @edelarua , I was wondering should we also have a snapshot for this too? @qiliu1013 please help to review this PR please. Thanks

**Comment by edelarua** [comment]
Please refer to https://github.com/insightsengineering/tlg-catalog/pull/116 for this table - I have opened a new PR due to the restructuring changes in TLG-C since this PR was created.

**Pull request closed without merging**
